# Generated by Django 5.0.7 on 2024-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sunlight_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('water_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('planting_season', models.CharField(blank=True, max_length=255, null=True)),
                ('harvest_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
