# Generated by Django 5.0.7 on 2024-08-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garden_plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('garden_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='designs.gardendesign')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_plants.plant')),
            ],
        ),
    ]
